spring:
  application:
    name: bookz-customer
  lifecycle:
    timeout-per-shutdown-phase: 1m

  datasource:
    url: jdbc:postgresql://localhost:5432/bookz-customer
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: "*"
        #changed default base url
      base-path: /monitor
      #changed port for the management
#  server:
#    port: 8181
  #getting health endpoint in detail
  endpoint:
    health:
      show-details: always
    #making info custom variable available
    info:
      env:
        enabled: true
  #ignored since beans is enabled by default
  #  endpoint:
  #    beans:
  #      access: read_only

  info:
    app:
      name: Bookz-Customer
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8282
  shutdown: graceful

authorization:
  key: "pY3R4t9sZ7wT2xE9kB1mC4vU8rQ6yF2aH7jL0qK3wM5nD8rB2pS5xG1tL4yW9zV6"